### ISSUE TITLE
Additional gateways disappear when Soisy plugin is active

### ISSUE THREAD

**Issue by mircobabini** [soisy/soisy-woocommerce-plugin#2]
Hello @kevincittadini, I think I found a bug but can't explain why.

Getting deep into it, I notices that the issues is coming from this line:
`$gateways = WC()->payment_gateways->payment_gateways();`

When this one is called, all the other Payment Methods I have disapper. Not the default ones, just the additional ones (PayPal Checkout, Stripe, and so on).

I changed that line to `$gateways = (new \WC_Payment_Gateways())->payment_gateways();` and it works as expected. I can see Soisy and the others as well.

Really can't explain this behaviour, if you want to check yourself I can provide you some staging access to the site. WC/WP and everything to the latest version. Already tried with all other plugins disabled.

**Comment by kevincittadini** [comment]
Hi @mircobabini.
Can you please provide details on your setup?
Versions and all 😄  You know the drill
