### ISSUE TITLE
Fatal error when $product object is null

### ISSUE THREAD

**Issue by diskyer** [soisy/soisy-woocommerce-plugin#3]
need check for $product is not null

https://github.com/soisy/soisy-woocommerce-plugin/blob/9a3f8a48477f4962c8bbb4c9f4db6e606f4262ee/templates/soisy-loan-block.php#L15
suggest:
```$priceToCheck = ( is_product() && ! empty( $product ) ) ? $product->get_price() : WC()->cart->total;```

https://github.com/soisy/soisy-woocommerce-plugin/blob/9a3f8a48477f4962c8bbb4c9f4db6e606f4262ee/templates/soisy-loan-block.php#L65
suggest:
```price: '<?php echo ( is_product() && ! empty( $product ) ) ? $product->get_price() : WC()->cart->total ?>',```

**Comment by kevincittadini** [comment]
Hi and thanks for reaching.
The `soisy-loan-block.php` template is meant to be used only in the following hooks: `woocommerce_before_cart_table` and `woocommerce_single_product_summary`. Also the `is_product` prevents a possibile null `$product` from being called. 

Therefore it's ok for you to have this edit on your personal copy of the plugin but this won't be a part of the official codebase, for now. 

Thanks for your time and for using Soisy.
